package velov.vue;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sql.DataSource;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.text.BadLocationException;
import swing.modele.ModeleTableList;
import velov.dao.IStationDAO;
import velov.dao.oracle.OracleDataSourceDAO;
import velov.dao.oracle.OracleStationDAO;
import velov.modele.Station;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Valentin
 */
public class Velov extends javax.swing.JFrame {

    private final List<Station> sta;
    private static IStationDAO  stationDAO;
    private static DataSource dataSourceDAO;
    private static Connection connexionBD;
    ModeleTableList mm;
    int valeurListe;
    private static boolean dialogPasse = false;
    private String username;
    private String password;

    /**
     * Creates new form Velov
     */
    public Velov() {
        sta = stationDAO.getLesStations();
        initComponents();
        if(!dialogPasse){
        initDialogRun();
        }else{
            for (int i = 0; i < bd.getLesStations().size(); i++) {
            mm.ajoutListe(bd.getLesStations().get(i));
        }
        }
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jList1.setEnabled(false);
        validModifButton.setVisible(false);  
        jButton7.setVisible(false);
        testButton.setEnabled(false);
        userNumberLabel.setVisible(true);
        passwordNumberLabel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        d = new javax.swing.JFileChooser();
        confirm = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        erreur = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        propos = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        confirmSuppr = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        initDialog = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        testButton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        enterButton = new javax.swing.JButton();
        connexionProgressBar = new javax.swing.JProgressBar();
        incorrectValue = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldPassword = new javax.swing.JPasswordField();
        jCheckBoxPassword = new javax.swing.JCheckBox();
        jButton7 = new javax.swing.JButton();
        userNumberLabel = new javax.swing.JLabel();
        passwordNumberLabel = new javax.swing.JLabel();
        tableCree = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        OKButton = new javax.swing.JButton();
        confirmSupprTable = new javax.swing.JDialog();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        supprTableOUI = new javax.swing.JButton();
        supprTableNON = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        creerButton = new javax.swing.JButton();
        supprButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        refreshButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        validModifButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        supprTabMenu = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        confirm.setTitle("Attention");
        confirm.setSize(new java.awt.Dimension(300, 200));

        jLabel6.setText("Ajouter cette station ?");

        jButton1.setText("Oui");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Non");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout confirmLayout = new javax.swing.GroupLayout(confirm.getContentPane());
        confirm.getContentPane().setLayout(confirmLayout);
        confirmLayout.setHorizontalGroup(
            confirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, confirmLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        confirmLayout.setVerticalGroup(
            confirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(confirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        erreur.setTitle("Erreur");
        erreur.setSize(new java.awt.Dimension(250, 150));

        jLabel7.setText("Il faut tout remplir !");

        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout erreurLayout = new javax.swing.GroupLayout(erreur.getContentPane());
        erreur.getContentPane().setLayout(erreurLayout);
        erreurLayout.setHorizontalGroup(
            erreurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, erreurLayout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addGroup(erreurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(erreurLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        erreurLayout.setVerticalGroup(
            erreurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(erreurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        propos.setSize(new java.awt.Dimension(420, 300));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/velov/vue/borne.JPG"))); // NOI18N
        jLabel8.setText("jLabel8");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Application Vélo'v");

        jLabel10.setText("Une application java Swing pour ");

        jLabel11.setText("le Grand Lyon");

        jLabel12.setText("Product Version : 1.0");

        jButton4.setText("Fermer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout proposLayout = new javax.swing.GroupLayout(propos.getContentPane());
        propos.getContentPane().setLayout(proposLayout);
        proposLayout.setHorizontalGroup(
            proposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(proposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(proposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(proposLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(proposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, proposLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, proposLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(26, 26, 26))
        );
        proposLayout.setVerticalGroup(
            proposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(proposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGroup(proposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(proposLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(proposLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        confirmSuppr.setSize(new java.awt.Dimension(420, 200));

        jLabel13.setText("Voulez-vous vraiment supprimer ?");

        jButton5.setText("Oui");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Non");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout confirmSupprLayout = new javax.swing.GroupLayout(confirmSuppr.getContentPane());
        confirmSuppr.getContentPane().setLayout(confirmSupprLayout);
        confirmSupprLayout.setHorizontalGroup(
            confirmSupprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmSupprLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(confirmSupprLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        confirmSupprLayout.setVerticalGroup(
            confirmSupprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmSupprLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel13)
                .addGap(35, 35, 35)
                .addGroup(confirmSupprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        initDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        initDialog.setTitle("Connexion");
        initDialog.setSize(new java.awt.Dimension(500, 400));

        jLabel14.setText("Connexion à la base de donnée :");

        jLabel15.setText("Nom d'utilisateur :");

        jLabel16.setText("Code BIP :");

        jTextFieldUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldUsernameKeyReleased(evt);
            }
        });

        testButton.setText("Tester la connexion");
        testButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testButtonActionPerformed(evt);
            }
        });

        jLabel17.setText("Pour commencer :");

        enterButton.setText("Acceder à l'application");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/velov/vue/Database-300x300.png"))); // NOI18N

        jTextFieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPasswordActionPerformed(evt);
            }
        });
        jTextFieldPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPasswordKeyReleased(evt);
            }
        });

        jCheckBoxPassword.setText("Voir le Mot de Passe");
        jCheckBoxPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPasswordActionPerformed(evt);
            }
        });

        jButton7.setText("Quitter");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        userNumberLabel.setText("8 caracteres nécessaires");

        passwordNumberLabel.setText("6 caracteres nécessaires");

        javax.swing.GroupLayout initDialogLayout = new javax.swing.GroupLayout(initDialog.getContentPane());
        initDialog.getContentPane().setLayout(initDialogLayout);
        initDialogLayout.setHorizontalGroup(
            initDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(initDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(24, 24, 24))
            .addGroup(initDialogLayout.createSequentialGroup()
                .addGroup(initDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(initDialogLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(testButton))
                    .addGroup(initDialogLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(initDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(initDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(initDialogLayout.createSequentialGroup()
                                .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(passwordNumberLabel))
                            .addGroup(initDialogLayout.createSequentialGroup()
                                .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(userNumberLabel))))
                    .addGroup(initDialogLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(initDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(incorrectValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(connexionProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(initDialogLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(initDialogLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(initDialogLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, initDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBoxPassword)
                .addGap(160, 160, 160))
        );
        initDialogLayout.setVerticalGroup(
            initDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(initDialogLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(initDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18))
                .addGap(32, 32, 32)
                .addGroup(initDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNumberLabel))
                .addGap(21, 21, 21)
                .addGroup(initDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordNumberLabel))
                .addGap(3, 3, 3)
                .addComponent(jCheckBoxPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(testButton)
                .addGap(21, 21, 21)
                .addComponent(connexionProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(incorrectValue)
                .addGap(18, 18, 18)
                .addComponent(enterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        tableCree.setTitle("Ajout des tables");
        tableCree.setSize(new java.awt.Dimension(420, 250));

        jLabel19.setText("Les tables STATION et ARRONDISSEMENT");

        jLabel20.setText(" n'étaient pas présentes dans votre Base de Donnée");

        jLabel21.setText("Pas de panique, elles y sont maintenant !");

        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tableCreeLayout = new javax.swing.GroupLayout(tableCree.getContentPane());
        tableCree.getContentPane().setLayout(tableCreeLayout);
        tableCreeLayout.setHorizontalGroup(
            tableCreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableCreeLayout.createSequentialGroup()
                .addGroup(tableCreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tableCreeLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel19))
                    .addGroup(tableCreeLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel20))
                    .addGroup(tableCreeLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel21))
                    .addGroup(tableCreeLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        tableCreeLayout.setVerticalGroup(
            tableCreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableCreeLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addGap(34, 34, 34)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(OKButton)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        confirmSupprTable.setTitle("ATTENTION");
        confirmSupprTable.setSize(new java.awt.Dimension(400, 200));

        jLabel22.setText("Voulez-vous vraiment supprimer les tables ?");

        jLabel23.setText("Cela redémarrera le logiciel");

        supprTableOUI.setText("Oui");
        supprTableOUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprTableOUIActionPerformed(evt);
            }
        });

        supprTableNON.setText("Non");
        supprTableNON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprTableNONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout confirmSupprTableLayout = new javax.swing.GroupLayout(confirmSupprTable.getContentPane());
        confirmSupprTable.getContentPane().setLayout(confirmSupprTableLayout);
        confirmSupprTableLayout.setHorizontalGroup(
            confirmSupprTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmSupprTableLayout.createSequentialGroup()
                .addGroup(confirmSupprTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(confirmSupprTableLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel22))
                    .addGroup(confirmSupprTableLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel23))
                    .addGroup(confirmSupprTableLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(supprTableOUI, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(supprTableNON, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        confirmSupprTableLayout.setVerticalGroup(
            confirmSupprTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmSupprTableLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addGroup(confirmSupprTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supprTableOUI)
                    .addComponent(supprTableNON))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Velo'v");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/velov/vue/bandeau.JPG"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setText("Numéro station :");

        jLabel3.setText("Nom station :");

        jLabel4.setText("Numéro arrondissement :");

        jLabel5.setText("Localisation :");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        creerButton.setText("Créer");
        creerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerButtonActionPerformed(evt);
            }
        });

        supprButton.setText("Supprimer");
        supprButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprButtonActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Lyon 1er arrondissement", "Lyon 2eme arrondissement", "Lyon 3eme arrondissement", "Lyon 4eme arrondissement", "Lyon 5eme arrondissement", "Lyon 6eme arrondissement", "Lyon 7eme arrondissement", "Lyon 8eme arrondissement", "Lyon 9eme arrondissement" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jTable1.setModel(mm);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addContainerGap())
        );

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        editButton.setText("Mode éditeur");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        validModifButton.setText("Valider la modification");
        validModifButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validModifButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 80, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(creerButton)
                                .addGap(71, 71, 71)
                                .addComponent(editButton)
                                .addGap(67, 67, 67)
                                .addComponent(supprButton)
                                .addGap(155, 155, 155))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(refreshButton)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(validModifButton, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36))))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshButton)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(creerButton)
                                .addComponent(supprButton))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(validModifButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jMenu1.setText("Fichier");

        jMenuItem1.setText("Ouvrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Sauvegarder");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        supprTabMenu.setText("Supprimer les tables");
        supprTabMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprTabMenuActionPerformed(evt);
            }
        });
        jMenu1.add(supprTabMenu);

        jMenuItem3.setText("Quitter");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("?");
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu2MenuSelected(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        int returnVal = d.showOpenDialog((Component) evt.getSource());

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File f = d.getSelectedFile();
            try {
                mm.charger(f.getAbsolutePath());

            } catch (IOException | ClassNotFoundException e) {
                System.out.println(e.getMessage());
            }
        }


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        int returnVal = d.showSaveDialog((Component) evt.getSource());

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File f = d.getSelectedFile();
            mm.sauvegarde(f.getAbsolutePath());
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void creerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerButtonActionPerformed
        // TODO add your handling code here:
        if (creerButton.getActionCommand().equals("Ok?")) {
            confirm.setVisible(true);
            jList1.setEnabled(false);
        } else if (creerButton.getActionCommand().equals("Créer")) {
            jTextField1.setEditable(true);
            jTextField2.setEditable(true);
            jTextField3.setEditable(true);
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jList1.setEnabled(true);
            jTable1.clearSelection();
            creerButton.setText("Ok?");
        }
    }//GEN-LAST:event_creerButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!jTextField1.getText().equals("") && !jTextField2.getText().equals("") && !jTextField3.getText().equals("") && !jList1.isSelectionEmpty()) {
            Integer numArrond;
            String num = jTextField1.getText();
            String nom = jTextField2.getText();
            String localisation = jTextField3.getText();
            numArrond = valeurListe + 1;
            Station nouvStation = new Station(num, nom, localisation, numArrond);
            bd.creerStation(nouvStation);
            mm.metAJourTable(bd.getLesStations());
            confirm.setVisible(false);
            jTextField1.setEditable(false);
            jTextField2.setEditable(false);
            jTextField3.setEditable(false);
            jList1.clearSelection();
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            creerButton.setText("Créer");
        } else {
            erreur.setVisible(true);
            confirm.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void supprButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprButtonActionPerformed
        // TODO add your handling code here:
        confirmSuppr.setVisible(true);
    }//GEN-LAST:event_supprButtonActionPerformed

  
    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        valeurListe = jList1.getSelectedIndex();
    }//GEN-LAST:event_jList1ValueChanged

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int ligneChoisi = jTable1.getSelectedRow();
        Object valNum = mm.getValueAt(ligneChoisi, 0);
        Object valNom = mm.getValueAt(ligneChoisi, 1);
        Object valNumArron = mm.getValueAt(ligneChoisi, 2);
        Object valLocal = mm.getValueAt(ligneChoisi, 3);
        jTextField1.setText((String) valNum);
        jTextField2.setText((String) valNom);
        jTextField3.setText((String) valLocal);
        int selectionListe = ((Integer) valNumArron) - 1;
        jList1.setSelectedIndex(selectionListe);
        jList1.ensureIndexIsVisible(jList1.getSelectedIndex());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        erreur.setVisible(false);
        jList1.setEnabled(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        confirm.setVisible(false);
        jList1.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        bd.quitter();
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        propos.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (mm.getRowCount() > 0) {
            Object ligneASuppr;
            if (jTable1.getSelectedRowCount() > 1) {
                int[] plusieursLignesSelec = jTable1.getSelectedRows();
                for (int i = plusieursLignesSelec.length - 1; i >= 0; i--) {
                    ligneASuppr = mm.getValueAt(plusieursLignesSelec[i], 0);
                    bd.supprimerStation((String) ligneASuppr);
                    mm.metAJourTable(bd.getLesStations());
                }
            } else {
                int ligneSelec = jTable1.getSelectedRow();
                ligneASuppr = mm.getValueAt(ligneSelec, 0);
                bd.supprimerStation((String) ligneASuppr);
                mm.metAJourTable(bd.getLesStations());
            }
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jList1.clearSelection();
            creerButton.setText("Créer");
            jList1.setEnabled(false);
        }
        confirmSuppr.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        confirmSuppr.setVisible(false);
        jTextField1.setEditable(true);
        jTextField2.setEditable(true);
        jTextField3.setEditable(true);
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jList1.setEnabled(true);
        jTable1.clearSelection();

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenu2MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu2MenuSelected
        // TODO add your handling code here:
        propos.setVisible(true);
    }//GEN-LAST:event_jMenu2MenuSelected

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        mm.metAJourTable(bd.getLesStations());
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        if (editButton.getActionCommand().equals("Mode éditeur")) {
            creerButton.setVisible(false);
            supprButton.setVisible(false);
            jTextField1.setEditable(true);
            jTextField2.setEditable(true);
            jTextField3.setEditable(true);
            jList1.setEnabled(true);
            validModifButton.setVisible(true);
            editButton.setText("Terminé");
        } else if (editButton.getActionCommand().equals("Terminé")) {
            creerButton.setVisible(true);
            supprButton.setVisible(true);
            jTextField1.setEditable(false);
            jTextField2.setEditable(false);
            jTextField3.setEditable(false);
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jList1.setEnabled(false);
            validModifButton.setVisible(false);
            editButton.setText("Mode éditeur");
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void validModifButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validModifButtonActionPerformed
        // TODO add your handling code here:
        int ligneSelec = jTable1.getSelectedRow();
        Object ligneASuppr = mm.getValueAt(ligneSelec, 0);
        bd.modifStation(jTextField1.getText(), jTextField2.getText(), jList1.getSelectedIndex() + 1, jTextField3.getText(), (String) ligneASuppr);
        mm.metAJourTable(bd.getLesStations());
    }//GEN-LAST:event_validModifButtonActionPerformed

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        // TODO add your handling code here:
        if(enterButton.getActionCommand().equals("Quitter")){
            bd.quitter();
            System.exit(0);
        }else if(enterButton.getActionCommand().equals("Accéder à l'application")){
            initDialog.setVisible(false);
            lancFrame();
        }
    }//GEN-LAST:event_enterButtonActionPerformed

    private void testButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testButtonActionPerformed
        // TODO add your handling code here:
        connexionProgressBar.setVisible(true);
        connexionProgressBar.setValue(100);
        connexionProgressBar.setStringPainted(true);
        connexionProgressBar.setForeground(Color.white);
        username = jTextFieldUsername.getText();
        password = String.valueOf(jTextFieldPassword.getPassword());
        this.bd = new OracleStationDAO(username,password);
        if(bd.testerConnexion()){
            if(!bd.tableStationExiste()){
            bd.creerTableStation();
            tableCree.setVisible(true);
             }else{
                
            }
            enterButton.setText("Accéder à l'application");
            incorrectValue.setText("Les données sont correctes");
            jButton7.setVisible(true);
            initDialog.setSize(500, 470);
        }else{
            incorrectValue.setText("Impossible de se connecter, données erronées");
            enterButton.setText("Quitter");
            jButton7.setVisible(true);
            initDialog.setSize(500, 420);
        }
    }//GEN-LAST:event_testButtonActionPerformed

    private void jCheckBoxPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPasswordActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxPassword.isSelected()){
            jTextFieldPassword.setEchoChar((char)0);
        }else{
            jTextFieldPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxPasswordActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        bd.quitter();
        System.exit(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextFieldUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUsernameKeyReleased
        // TODO add your handling code here:
        if(jTextFieldUsername.getText().length()!=8){
            try {
                if(!jTextFieldUsername.getText(0, 1).contains("p")){
                    userNumberLabel.setText("Commence par un 'p'");
                }else{
                    userNumberLabel.setText("8 caracteres nécessaires");
                }
                    userNumberLabel.setVisible(true);
                testButton.setEnabled(false);
            } catch (BadLocationException ex) {
                Logger.getLogger(Velov.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            try {
                if(!jTextFieldUsername.getText(0, 1).contains("p")){
                    userNumberLabel.setVisible(true);
                    userNumberLabel.setText("Commence par un 'p'");
                }else{
                userNumberLabel.setVisible(false);
                if((jTextFieldPassword.getPassword().length==6))
                    testButton.setEnabled(true);
                }
            } catch (BadLocationException ex) {
                Logger.getLogger(Velov.class.getName()).log(Level.SEVERE, null, ex);
            }
                }
    }//GEN-LAST:event_jTextFieldUsernameKeyReleased

    private void jTextFieldPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPasswordKeyReleased
        // TODO add your handling code here:
        if(jTextFieldPassword.getPassword().length!=6){
            passwordNumberLabel.setVisible(true);
            testButton.setEnabled(false);
        }else{
            passwordNumberLabel.setVisible(false);
            if(jTextFieldUsername.getText().length()==8)
                testButton.setEnabled(true);
                }
    }//GEN-LAST:event_jTextFieldPasswordKeyReleased

    private void jTextFieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPasswordActionPerformed

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        // TODO add your handling code here:
        tableCree.setVisible(false);
    }//GEN-LAST:event_OKButtonActionPerformed

    private void supprTabMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprTabMenuActionPerformed
        // TODO add your handling code here:
        confirmSupprTable.setVisible(true);  
    }//GEN-LAST:event_supprTabMenuActionPerformed

    private void supprTableNONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprTableNONActionPerformed
        // TODO add your handling code here:
        confirmSupprTable.setVisible(false);
    }//GEN-LAST:event_supprTableNONActionPerformed

    private void supprTableOUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprTableOUIActionPerformed
        bd.supprTable();  
        bd.quitter();
        this.dispose(); 
        initDialogRun();
        confirmSupprTable.setVisible(false);
    }//GEN-LAST:event_supprTableOUIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Velov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Velov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Velov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Velov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try{
                dataSourceDAO = OracleDataSourceDAO.getOracleDataSourceDAO();
                stationDAO = new OracleStationDAO();
                stationDAO.setDataSource(dataSourceDAO);
                connexionBD = dataSourceDAO.getConnection();
                stationDAO.setConnection(connexionBD);
                new Velov().setVisible(true);
            }catch(SQLException ex){
                Logger.getLogger(Velov.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        
    }
    
    public void initDialogRun(){
        initDialog.setVisible(true);
        enterButton.setText("Quitter");
        connexionProgressBar.setVisible(false);
    }

    public void lancFrame(){
        dialogPasse = true;
        new Velov().setVisible(true);
    }
    
    private void formWindowClosing(java.awt.event.WindowEvent evt){
        bd.quitter();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKButton;
    private javax.swing.JDialog confirm;
    private javax.swing.JDialog confirmSuppr;
    private javax.swing.JDialog confirmSupprTable;
    private javax.swing.JProgressBar connexionProgressBar;
    private javax.swing.JButton creerButton;
    private javax.swing.JFileChooser d;
    private javax.swing.JButton editButton;
    private javax.swing.JButton enterButton;
    private javax.swing.JDialog erreur;
    private javax.swing.JLabel incorrectValue;
    private javax.swing.JDialog initDialog;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBoxPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPasswordField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldUsername;
    private javax.swing.JLabel passwordNumberLabel;
    private javax.swing.JDialog propos;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton supprButton;
    private javax.swing.JMenuItem supprTabMenu;
    private javax.swing.JButton supprTableNON;
    private javax.swing.JButton supprTableOUI;
    private javax.swing.JDialog tableCree;
    private javax.swing.JButton testButton;
    private javax.swing.JLabel userNumberLabel;
    private javax.swing.JButton validModifButton;
    // End of variables declaration//GEN-END:variables
}
